### ISSUE TITLE
genome_cluster may have a bug.

### ISSUE THREAD

**Issue by wataken1127** [const-ae/tidygenomics#5]
Thank you for your great package.

genome_cluster does not work well when the range has several numbers of digits.
for example,

x2 <- data.frame(id = 1:3, bla=letters[1:3],
                 chromosome = c("chr1", "chr1", "chr1"),
                 start = c(1696, 2846, 945),
                 end = c(1700, 2850, 946))
genome_cluster(x2, by=c("chromosome", "start", "end"))

dose not work.
cluster_id of "a" and "c" is "0", and that of "b" is "1".
(it should be 0, 1, and 2, right?)

I guess genome_cluster cannot distinguish ranges with different numbers of digits like 1700 and 945.
Do you have any good idea?

Thanks,
Kentaro

**Comment by const-ae** [comment]
Hi Kentaro,

You are absolutely right, that is a bug and I am very sorry if it caused you any inconveniences.
The problem is not related to the number of digits, but seems to be related to the order of the ranges. I am pretty sure the offending method is [cluster_interval](https://github.com/const-ae/tidygenomics/blob/master/src/cluster_interval.cpp#L94).

I will try to fix this as soon as possible, but I haven't looked into this code for about two years, so I might take a day or two to figure out what is happening there. 

I will comment again, when I understand what is happening there.

Best Regards,
Constantin

**Comment by wataken1127** [comment]
Dear Constantin,
Thank you for your prompt reply.
I will wait for the update.

Regards,
Kentaro

**Comment by const-ae** [comment]
I have fixed the issue, now the clustering returns the expected numbers

``` r
library(tidygenomics)
x2 <- data.frame(id = 1:3, bla=letters[1:3],
                 chromosome = c("chr1", "chr1", "chr1"),
                 start = c(1696, 2846, 945),
                 end = c(1700, 2850, 946))
genome_cluster(x2, by=c("chromosome", "start", "end"))
#> # A tibble: 3 x 6
#>      id bla   chromosome start   end cluster_id
#>   <int> <fct> <fct>      <dbl> <dbl>      <dbl>
#> 1     1 a     chr1        1696  1700          1
#> 2     2 b     chr1        2846  2850          2
#> 3     3 c     chr1         945   946          0
```

<sup>Created on 2019-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

To get the latest version, install the package from GitHub
```r
devtools::install_github("const-ae/tidygenomics")
```

I will try push the updated version to CRAN within the next days. Thank you again, for raising the issue.

**Comment by const-ae** [comment]
The fixed version is on [CRAN](https://cran.r-project.org/package=tidygenomics) now.
