### ISSUE TITLE
Performance as compared to IRanges?

### ISSUE THREAD

**Issue by liutiming** [const-ae/tidygenomics#7]
I love this package!

Wondering if you have done profiling as compared to IRanges?

**Comment by const-ae** [comment]
Hey, thanks. I am always happy to hear when somebody enjoys my packages :)

> Wondering if you have done profiling as compared to IRanges?

Well, not directly. But I am in fact using IRanges heavily on the inside (for example [here](https://github.com/const-ae/tidygenomics/blob/master/R/intersect.R#L76)), so that the package could be considered a convenient wrapper that makes it easy to use IRanges from the tidyverse :)

**Comment by liutiming** [comment]
Thanks :)
